// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'chrome-register-failed'
  | 'hello-section-header'
  | 'hello-section-sidenav'
  | 'main-tab-button'
  | 'prefs-cli-hint-empty'
  | 'prefs-cli-hint-missing'
  | 'prefs-cli-hint-ok'
  | 'prefs-cli-label'
  | 'prefs-mode-hint'
  | 'prefs-mode-item-acceptEdits'
  | 'prefs-mode-item-default'
  | 'prefs-mode-item-plan'
  | 'prefs-mode-label'
  | 'prefs-pane-intro'
  | 'prefs-pane-label'
  | 'prefs-pane-title'
  | 'prefs-workspace-browse'
  | 'prefs-workspace-hint-empty'
  | 'prefs-workspace-hint-missing'
  | 'prefs-workspace-hint-ok'
  | 'prefs-workspace-hint-relative'
  | 'prefs-workspace-label';
