// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "workspacePath": string;
      "workspaceMode": string;
      "defaultPermissionMode": string;
      "cliPathOverride": string;
      "autoShowPane": boolean;
      "dockWidth": number;
      "dockOpen": boolean;
      "deepseekApiKey": string;
      "showUsage": boolean;
    };
  }
}
